# This is a basic workflow to help you get started with Actions
- name: Lint Ren'Py Project
  # You may pin to the exact commit or the version.
  # uses: ProjectAliceDev/renpy-lint-action@91b9542165a707ec71ff541b6c7bda113a581caf
  uses: ProjectAliceDev/renpy-lint-action@v1.1.1
  with:
    # The version of the Ren'Py SDK to use
    sdk-version: # default is 7.3.2
    # The path to the directory where the project exists
    project-dir: # default is .
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
